django/2018/facemash/facemash/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('utilisateur.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

django/2018/facemash/utilisateur/urls.py
from django.urls import path
from . import views

app_name = 'utilisateur'
urlpatterns = [
    path('', views.liste_utilisateurs, name='liste_utilisateurs'),
    path('liste_votes/', views.liste_votes, name='liste_votes'),
    path('voir_utilisateur/<int:user>/', views.voir_utilisateur, name='voir_utilisateur'),
    path('comparer/', views.voter, name='voter'),
    path('edit/<int:user>/', views.edit, name='edit'),
    path('nouveau/', views.edit, name='edit_nouveau'),
    path('voter/<int:user1>/<int:user2>', views.voter, name='voter_pour'),
]

django/2018/facemash/utilisateur/models.py
from django.db import models
from django.forms import ModelForm

from math import pow


class Utilisateur(models.Model):
    photo = models.ImageField(upload_to= 'girls')
    nom   = models.CharField(max_length=100)
    email = models.EmailField(default="", null=True, blank=True)
    votes = models.IntegerField(default=0, editable=False)
    score = models.FloatField(default=1000, editable=False)
    
    def comparaison(self, score, utilisateur2):
        k = 10
        if self.votes < 30:
            k = 30
        elif self.score < 2400:
            k = 15
        self.score += k * ( score - 1/(1+pow(10,-(self.score-utilisateur2.score)/400.0)) )
        self.votes += 1
    
    def __unicode__(self):
        return self.nom
    
# Facemash espionne les gens
class Votant(models.Model):
    ip       = models.GenericIPAddressField(default="0.0.0.0")
    voted    = models.ForeignKey(Utilisateur, related_name='+', on_delete=models.CASCADE)
    notVoted = models.ForeignKey(Utilisateur, related_name='+', on_delete=models.CASCADE)
    date     = models.DateTimeField() 
    
    def __unicode__(self):
        return self.ip


class UtilisateurEditForm(ModelForm):
    class Meta:
        model = Utilisateur
        fields = ('photo','nom', 'email')

django/2018/facemash/utilisateur/views.py
from utilisateur.models import *
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from datetime import datetime
from random import randint

def liste_utilisateurs(request):
    utilisateurs = Utilisateur.objects.order_by('-score', 'nom')
    return render(request, 'utilisateur/liste_utilisateurs.html', {'utilisateurs': utilisateurs})

def liste_votes(request):
    votes = Votant.objects.all()
    return render(request, 'utilisateur/liste_votes.html', {'votes': votes})
    
def voir_utilisateur(request, user):
    utilisateur = Utilisateur.objects.get(id=user)
    return render(request, 'utilisateur/voir_utilisateur.html', {'utilisateur': utilisateur})

def edit(request, user=None):
    if user is not None:
        utilisateur = Utilisateur.objects.get(id=user)
    else:
        utilisateur = None
    if request.method == 'POST':
        form = UtilisateurEditForm(request.POST, request.FILES, instance=utilisateur)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        else:
            int("not valid!")
    else:
        form = UtilisateurEditForm(instance=utilisateur)
    return render(request, 'utilisateur/edit.html', {'form': form})

def voter(request, user1=None, user2=None): #user1 et le/la gagnant du vote
    
    if (user1 is not None) and (user2 is not None):
        utilisateur1 = Utilisateur.objects.get(id=user1)
        utilisateur2 = Utilisateur.objects.get(id=user2)
        utilisateur1.comparaison(1, utilisateur2)
        utilisateur2.comparaison(0, utilisateur1)
        utilisateur1.save()
        utilisateur2.save()
        votant          = Votant()
        votant.ip       = request.META['REMOTE_ADDR']
        votant.voted    = utilisateur1
        votant.notVoted = utilisateur2
        votant.date     = datetime.now()
        votant.save()
        return HttpResponseRedirect("/utilisateur/comparer")
        
    else:
        nbUsers = len(Utilisateur.objects.all())
        if nbUsers <2:
            return HttpResponse("Non mais il faut au moins deux utilisateurs !")
        user1 = randint(1,nbUsers)
        user2 = (randint(1,nbUsers-1) + user1-1)%nbUsers+1 # astuce pour que user2 != user1 sans faire de retirage
        print(user1, user2, nbUsers)
        utilisateur1 = Utilisateur.objects.get(id=user1)
        utilisateur2 = Utilisateur.objects.get(id=user2)
        return render(request, 'utilisateur/vote.html', {'utilisateur1': utilisateur1, 'utilisateur2': utilisateur2})

django/2018/facemash/templates/main.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="fr">
<head>
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
<a href="{% url 'utilisateur:liste_utilisateurs' %}">Liste des utilisateurs</a> | <a href="{% url 'utilisateur:edit_nouveau' %}">Nouvel utilisateur</a> | <a href="{%url 'utilisateur:voter' %}">Voter</a> | <a href="{% url 'utilisateur:liste_votes' %}">Voir les votants</a>
<br />    
{% block content %}{% endblock %}
</body>
</html>

django/2018/facemash/templates/utilisateur/edit.html
{% extends "main.html" %}

{% block title %}Editer un utilisateur{% endblock %}

{% block content %}
<form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
{{ form }}
<input type="submit" value="Submit" />
</form>
{% endblock %}

django/2018/facemash/templates/utilisateur/liste_utilisateurs.html
{% extends "main.html" %}

{% block title %}Liste des utilisateurs{% endblock %}

{% block content %}

<br/>
<table>
{%for user in utilisateurs%}
<tr>
	<td>{{user.score|floatformat:"-1"}}</td>
	<td><a href="{% url 'utilisateur:voir_utilisateur' user.id%}">{{user.nom}}</a></td>
	<td><a href="{% url 'utilisateur:edit' user.id%}">éditer</a></td>
</tr>	
{%endfor%}
</table>
{% endblock %}

django/2018/facemash/templates/utilisateur/liste_votes.html
{% extends "main.html" %}

{% block title %}Liste des votes{% endblock %}

{% block content %}

<br/>
<table>
{%for vote in votes%}
<tr>
	<td>{{vote.ip}}</td>
	<td>a voté pour : <a href="{% url 'utilisateur:voir_utilisateur' vote.voted.id%}">{{vote.voted.nom}}</a></td>
	<td>en défaveur de <a href="{% url 'utilisateur:voir_utilisateur' vote.notVoted.id%}">{{vote.notVoted.nom}}</a></td>
	<td>{{vote.date}}</td>
</tr>	
{%endfor%}
</table>
{% endblock %}

django/2018/facemash/templates/utilisateur/voir_utilisateur.html
{% extends "main.html" %}

{% block title %}Voir un utilisateur{% endblock %}



{% block content %}

<img src="{{ MEDIA_URL }}/{{utilisateur.photo}}">
<br/>
<strong>{{utilisateur.nom}}</strong> {{utilisateur.email}}
<br/>
score : {{utilisateur.score}} ({{utilisateur.votes}} votes)


{% endblock %}

django/2018/facemash/templates/utilisateur/vote.html
{% extends "main.html" %}

{% block title %}Voter pour un utilisateur{% endblock %}



{% block content %}
Cliquer sur un utilisateur pour voter pour lui <br />

<a href="{%url 'utilisateur:voter_pour' utilisateur1.id utilisateur2.id %}"><img src="{{ MEDIA_URL }}/{{utilisateur1.photo}}"></a>
<a href="{%url 'utilisateur:voter_pour' utilisateur2.id utilisateur1.id %}"><img src="{{ MEDIA_URL }}/{{utilisateur2.photo}}"></a>



{% endblock %}